name: check

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "^1.19"

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go command
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: verify
        run: make verify
      - name: make for test
        run: make
